name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Farjad.sln'
      
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell    
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore dependencies
      run: nuget restore $SOLUTION
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION -p:Configuration=$env:BUILD_CONFIG -p:Platform="Any CPU" --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.FARJAD}} -SkipDuplicate

    - name: Publish to github
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget add source --username mohrmz --password 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 --name github https://nuget.pkg.github.com/mohrmz/index.json
      run: dotnet nuget push **\*.nupkg --source github